USE [master]
GO

CREATE DATABASE [GADATA_RPT] 
ON PRIMARY 
( NAME = N'GADATA_RPT', 
  FILENAME = N'E:\SQL-Data\User\MSSQL\GADATA_RPT.mdf' , 
  SIZE = 5GB , 
  MAXSIZE = UNLIMITED, 
  FILEGROWTH = 1GB ), -- Changed to fixed growth
FILEGROUP [GADATA_RPT_FullTextIndex] 
( NAME = N'GADATA_RPT_FTI', 
  FILENAME = N'I:\SQL-Data\User\MSSQL\GADATA_RPT_FTI.ndf' , 
  SIZE = 10GB , 
  MAXSIZE = 20GB , 
  FILEGROWTH = 524288KB ),
 FILEGROUP [GADATA_RPT_FileStreamGroup] CONTAINS FILESTREAM (
    NAME = N'GADATA_RPT_FS', 
	FILENAME = N'I:\SQL-Data\User\MSSQL\GADATA_RPT_FS')
 LOG ON 
( NAME = N'GADATA_RPT_log', 
  FILENAME = N'E:\SQL-Log\GADATA_RPT_log.ldf' ,
  SIZE = 5696KB , 
  MAXSIZE = 20GB ,
  FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF, FILESTREAM (NON_TRANSACTED_ACCESS = FULL, DIRECTORY_NAME = N'SQL-FS')
GO