USE [GADATA_RPT]
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
BEGIN
--
    CREATE FULLTEXT CATALOG [GADATA_RPT_FTCatalog] WITH ACCENT_SENSITIVITY = ON
		AS DEFAULT
		AUTHORIZATION [dbo]
END
GO

-- Add filegroup to catalog
ALTER FULLTEXT CATALOG [GADATA_RPT_FTCatalog] 
REBUILD WITH ACCENT_SENSITIVITY = ON;

ALTER DATABASE [GADATA_RPT] SET QUERY_STORE (
    OPERATION_MODE = READ_WRITE,
    CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 60),
    DATA_FLUSH_INTERVAL_SECONDS = 3600,
    MAX_STORAGE_SIZE_MB = 20480, -- Increased to 20GB
    QUERY_CAPTURE_MODE = AUTO,
    SIZE_BASED_CLEANUP_MODE = AUTO,
    MAX_PLANS_PER_QUERY = 500,
    WAIT_STATS_CAPTURE_MODE = ON
);